return {
	-- "nvim-tree/nvim-tree.lua",
	-- config = function()
	-- 	require("nvim-tree").setup({
	-- 		sort = {
	-- 			sorter = "case_sensitive",
	-- 		},
	-- 		sync_root_with_cwd = true,
	-- 		view = {
	-- 			width = 30,
	-- 			relativenumber = true,
	-- 		},
	-- 		renderer = {
	-- 			group_empty = true,
	-- 			root_folder_label = false,
	-- 		},
	-- 		filters = {
	-- 			dotfiles = true,
	-- 		},
	-- 	})
	--
	-- 	vim.keymap.set("n", "<leader>e", ":NvimTreeToggle<CR>")
	-- end,
}
